config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/post.rb
class Post < ActiveRecord::Base
  enum status: { submitted: 0, approved: 1, rejected: 2 }

  belongs_to :user
  validates_presence_of :date, :rationale, :overtime_request
  validates :overtime_request, numericality: { greater_than: 0.0 }

  scope :posts_by, ->(user) { where(user_id: user.id) }

  after_save :confirm_audit_log, if: :submitted?
  after_save :un_confirm_audit_log, if: :rejected?

  private

  def confirm_audit_log
    audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
    audit_log.confirmed! if audit_log
  end

  def un_confirm_audit_log
    audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
    audit_log.pending! if audit_log
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :approve]

  def index
    @posts = Post.posts_by(current_user).page(params[:page]).per(10)
  end

  def approve
    authorize @post
    @post.approved!

    redirect_to root_path, notice: "The post has been approved"
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: 'Your post was created successfully'
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: 'Your post was edited successfully'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Your post was deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale, :status, :overtime_request)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Overtime App Notification", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :overtime_request, class: "col-sm-2 control-label" %>
    <%= f.text_field :overtime_request, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <%= f.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rationale, class: "col-sm-2 control-label" %>
    <%= f.text_area :rationale, class: "form-control" %>
  </div>

  <%= render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser' %>

  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id %>
	</td>
  <td>
    <%= post.overtime_request %>
  </td>
	<td>
		<%= post.date %>
	</td>
	<td>
		<%= post.user.full_name %>
	</td>
	<td>
		<%= link_to truncate(post.rationale), post %>
	</td>
  <td>
    <%= status_label post.status %>
  </td>
	<td>
		<%= link_to '', edit_post_path(post), id: "edit_#{post.id}", class: 'glyphicon glyphicon-pencil index-icons' if policy(post).update? %>
	</td>
	<td>
		<%= link_to '', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index",  class: 'glyphicon glyphicon-trash index-icons', data: { confirm: 'Are you sure?' } %>
	</td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'approved' %>
  <%= f.label :status, 'Approved' %>

  <%= f.radio_button :status, 'rejected' %>
  <%= f.label :status, 'Rejected' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
      <th>
        Overtime Requested
      </th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
      <th>`
        Status
      </th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody id="posts">
		<%= render @posts %>
	</tbody>
</table>

<div id="paginator">
  <%= paginate @posts, remote: true %>
</div>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div>
  <h2><%= @post.rationale %></h2>
</div>

<hr/>

<div class="well">
  <div>
    <h3><span>Overtime Amount Requested:</span> <%= @post.overtime_request %></h3>
  </div>

  <div>
    <h3><span>Employee:</span> <%= @post.user.full_name %></h3>
  </div>

  <div>
    <h3><span>Date:</span> <%= @post.date %></h3>
  </div>

  <div>
    <h3><span>Current Stage of Approval</span>: <%= @post.status %></h3>
  </div>

</div>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" if policy(@post).update? %>